### ISSUE TITLE
영화 예고편을 다운 받읍시다.

### ISSUE THREAD

**Issue by 026854** [byeongcheoljo/Clim#1]
***예시***
"https://www.naver.com/",
"https://www.naver.com/",
"https://www.naver.com/"

영준 @YoungJunSohn 
- [x] "얼리전트",
- [x] "비긴 어게인",
- [x] "더 셰프",
- [x] "캡틴 아메리카: 윈터 솔져",
- [x] "혹성탈출: 반격의 서막",
- [x] "엔들리스 러브",

지은

- [x] "엑소더스 : 신들과 왕들",
- [x] "허큘리스",
- [x] "인디펜던스 데이: 리써전스",
- [x] "인터스텔라",
- [x] "킹스맨: 시크릿 에이전트",
- [x] "라이프 오브 파이",

재현 @kjh576 

- [x] "러브 액츄얼리",
- [x] "메이즈 러너: 스코치 트라이얼",
- [x] "미 비포 유",
- [x] "미션 임파서블: 로그네이션",
- [x] "나우 이즈 굿",
- [x] "퍼시픽림",

승현 @ssh0820 

- [x] "007 스펙터",
- [x] "테이큰 2",
- [x] "테이큰 3",  
- [x] "19곰 테드2",
- [x] "대니쉬 걸",
- [x] "호빗: 다섯 군대 전투",

병철 @byeongcheoljo 

- [x] "헝거게임: 캣칭 파이어",
- [x] "이미테이션 게임",
- [x] "노벰버 맨",
- [x] "제5침공",
- [x] "빅 쇼트",
- [x] "익스펜더블 3",

규범 @HanGyuBeom 

- [x] "안녕, 헤이즐",
- [x] "더 퍼지: 거리의 반란",
- [x] "트랜스포머: 사라진 시대",
- [x] "워크래프트",
- [x] "월드워Z",
- [x] "엑스맨: 데이즈 오브 퓨처 패스트",

성표 @SUNGPYOHONG 

- [x] "그 시절, 우리가 좋아했던 소녀",
- [x] "더 기버: 기억전달자",
- [x] "버킷리스트: 죽기 전에 꼭 하고 싶은 것들",
- [x] "아메리칸 스나이퍼",
- [x] "인셉션",
- [x] "호빗: 뜻밖의 여정",

큰켱 @woodeekim 

- [x] "분노의 질주: 더 세븐",
- [x] "히트맨: 에이전트 47",
- [x] "런던 해즈 폴른",
- [x] "세기의 매치",
- [x] "아델라인: 멈춰진 시간",

**Comment by byeongcheoljo** [comment]
"<iframe width="879" height="494" src="https://www.youtube.com/embed/HFU496S1J5A" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>",

"<iframe width="879" height="494" src="https://www.youtube.com/embed/LCbFEOVQ9EE" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>",

"<iframe width="879" height="494" src="https://www.youtube.com/embed/fZGX3vgGeIc" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>",

"<iframe width="879" height="494" src="https://www.youtube.com/embed/EA_bRDDOQL8" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>",

"<iframe width="879" height="494" src="https://www.youtube.com/embed/5NjZfn_3rMc" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>",

"<iframe width="879" height="494" src="https://www.youtube.com/embed/GSQNFFhErAc" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>",

**Comment by HanGyuBeom** [comment]
"안녕, 헤이즐", https://youtu.be/d3UKWHvXcUg
  "더 퍼지: 거리의 반란", https://youtu.be/Baja9cLiX0E
  "트랜스포머: 사라진 시대", https://youtu.be/08gHMAwd6jg
  "워크래프트", https://youtu.be/jRCow6UeRZU
  "월드워Z", https://youtu.be/wXOcmczgGec
  "엑스맨: 데이즈 오브 퓨처 패스트" https://youtu.be/GqlpFOt0CZs

**Comment by HanGyuBeom** [comment]
"<iframe width="1179" height="786" 
src="https://www.youtube.com/embed/d3UKWHvXcUg" frameborder="0" 
allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" 
allowfullscreen></iframe>",

"<iframe width="1179" height="663" 
src="https://www.youtube.com/embed/Baja9cLiX0E" frameborder="0" 
allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" 
allowfullscreen></iframe>",

"<iframe width="1179" height="663" 
src="https://www.youtube.com/embed/08gHMAwd6jg" frameborder="0" 
allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" 
allowfullscreen></iframe>",

"<iframe width="1179" height="663" 
src="https://www.youtube.com/embed/jRCow6UeRZU" frameborder="0" 
allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" 
allowfullscreen></iframe>",

"<iframe width="1179" height="663" 
src="https://www.youtube.com/embed/wXOcmczgGec" frameborder="0" 
allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" 
allowfullscreen></iframe>",

"<iframe width="1179" height="663" 
src="https://www.youtube.com/embed/GqlpFOt0CZs" frameborder="0" 
allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" 
allowfullscreen></iframe>",

**Comment by SUNGPYOHONG** [comment]
"<iframe width="1056" height="704 src='https://www.youtube.com/embed/GhdqjzOkC5k" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>",
"<iframe width="1056" height="704" src="https://www.youtube.com/embed/UWxqNtnF5M0" frameborder="0" allow="ccelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>",
"<iframe width="1252" height="704" src="https://www.youtube.com/embed/ML3sFRLVNuE" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>",
"<iframe width="1252" height="704" src="https://www.youtube.com/embed/ZCi-R0ytmDQ" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>",
"<iframe width="939" height="704" src="https://www.youtube.com/embed/hx1fqhNoH8A" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>",
"<iframe width="1056" height="704" src="https://www.youtube.com/embed/iLBP3s2_AjA" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>",

**Comment by YoungJunSohn** [comment]
"<iframe width="1280" height="720" src="https://www.youtube.com/embed/0iHHeuOvZmg" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>",
"<iframe width="1280" height="704" src="https://www.youtube.com/embed/ssMROHVsoAk" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>",
"<iframe width="1280" height="720" src="https://www.youtube.com/embed/IopG5SNXmMU" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>",
"<iframe width="1280" height="720" src="https://www.youtube.com/embed/D4Z2nEdzkdc" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>",
"<iframe width="1280" height="720" src="https://www.youtube.com/embed/PSNtfXDLWoM" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>",
"<iframe width="1280" height="720" src="https://www.youtube.com/embed/6EDBGGcNp9s" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>",

"얼리전트",
  "비긴 어게인",
  "더 셰프",
  "캡틴 아메리카: 윈터 솔져",
  "혹성탈출: 반격의 서막",
  "엔들리스 러브",

**Comment by ssh0820** [comment]
"https://youtu.be/S_Ox7g1rig0",
"https://youtu.be/Zlv9HBmChQM",
"https://youtu.be/GMkY7LawUcg",
"https://youtu.be/W_C0N9L9ajs",
"ttps://youtu.be/M34cK2BohGM",
"https://youtu.be/FaP7kM-UK-A",

**Comment by ssh0820** [comment]
"<iframe width="879" height="494" src="https://www.youtube.com/embed/S_Ox7g1rig0" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>",

"<iframe width="876" height="584" src="https://www.youtube.com/embed/Zlv9HBmChQM" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>",

"<iframe width="876" height="493" src="https://www.youtube.com/embed/GMkY7LawUcg" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>",

"<iframe width="876" height="493" src="https://www.youtube.com/embed/W_C0N9L9ajs" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>",

"<iframe width="876" height="493" src="https://www.youtube.com/embed/M34cK2BohGM" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>",

"<iframe width="876" height="493" src="https://www.youtube.com/embed/taji0FUv1sk" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>",

**Comment by woodeekim** [comment]
"<iframe width="976" height="549" src="https://www.youtube.com/embed/aSvpm_sfYys" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>",

"<iframe width="976" height="549" src="https://www.youtube.com/embed/zhiAssdzqZo" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>",

"<iframe width="976" height="549" src="https://www.youtube.com/embed/jJnvcUFjd4g" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>",

"<iframe width="976" height="549" src="https://www.youtube.com/embed/uC1LxRRCurw" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>",

"<iframe width="976" height="549" src="https://www.youtube.com/embed/7T8JWpAwcVE" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>",

**Comment by 026854** [comment]
"<iframe width="879" height="494" src="https://www.youtube.com/embed/naDOI2LBZPQ" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>",
"<iframe width="879" height="494" src="https://www.youtube.com/embed/NcOhD2_VqB4" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>",
"<iframe width="879" height="494" src="https://www.youtube.com/embed/wACNe5jpLGw" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>",
"<iframe width="879" height="494" src="https://www.youtube.com/embed/d2VN6NNa9BE" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>",
"<iframe width="879" height="494" src="https://www.youtube.com/embed/SW6EKneLyCI" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>",
"<iframe width="879" height="586" src="https://www.youtube.com/embed/JlZV4Ietg5M" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>"

**Comment by hikjh** [comment]
'<iframe width="1280" height="720" src="https://www.youtube.com/embed/K-mdSC6jujU" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
'<iframe width="1280" height="720" src="https://www.youtube.com/embed/haiiUlqC7Ns" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
'<iframe width="1280" height="720" src="https://www.youtube.com/embed/XRbSnTyZttU" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
'<iframe width="1280" height="720" src="https://www.youtube.com/embed/7udqxxpMCK4" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
'<iframe width="1017" height="753" src="https://www.youtube.com/embed/kU1mHiXbzyM" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
'<iframe width="1280" height="720" src="https://www.youtube.com/embed/yNQE9Gm54EQ" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
